import { StyleSheet } from 'react-native';

import { palette, type AppTheme } from '@/theme/colors';

export const createStyles = (theme: AppTheme) =>
  StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    scroll: {
      flex: 1,
    },
    scrollContent: {
      paddingTop: 16,
    },
    fireworksLayer: {
      position: 'absolute',
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      zIndex: 2,
    },
    fireworksHalo: {
      position: 'absolute',
      width: 128,
      height: 128,
      borderRadius: 64,
      backgroundColor: 'rgba(110, 231, 183, 0.22)',
    },
    fireworkParticle: {
      position: 'absolute',
      shadowColor: theme.colors.shadow,
      shadowOpacity: 0.18,
      shadowOffset: { width: 0, height: 6 },
      shadowRadius: 10,
      elevation: 6,
    },
    emojiRainItem: {
      position: 'absolute',
    },
    emojiRainItemOffset: {
      top: -72,
    },
    emojiRainText: {
      fontSize: 28,
    },
    stickyHeader: {
      backgroundColor: theme.colors.background,
      zIndex: 1,
    },
    headerContent: {
      paddingHorizontal: 20,
      gap: 16,
      paddingBottom: 16,
    },
    bodyContent: {
      paddingHorizontal: 20,
      gap: 16,
    },
    topBar: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 8,
    },
    iconButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: theme.colors.border,
      shadowColor: theme.colors.shadow,
      shadowOpacity: 0.35,
      shadowOffset: { width: 0, height: 6 },
      shadowRadius: 12,
      elevation: 4,
    },
    iconButtonPressed: {
      opacity: 0.85,
    },
    screenTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: theme.colors.textPrimary,
    },
    tabRail: {
      gap: 10,
      paddingRight: 12,
    },
    tabPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      borderRadius: 999,
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surface,
    },
    tabPillActive: {
      backgroundColor: palette.mintStrong,
      borderColor: palette.mintStrong,
    },
    tabPillPressed: {
      opacity: 0.86,
    },
    tabPillText: {
      fontSize: 13,
      fontWeight: '600',
      color: theme.colors.textSecondary,
    },
    tabPillTextActive: {
      color: theme.colors.textInverse,
    },
    metricLabel: {
      fontSize: 12,
      color: theme.colors.textSecondary,
      textTransform: 'uppercase',
      letterSpacing: 0.6,
    },
    summaryRow: {
      flexDirection: 'row',
      gap: 10,
    },
    summaryCard: {
      flex: 1,
      borderRadius: 20,
      paddingVertical: 14,
      paddingHorizontal: 12,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surface,
      shadowColor: theme.colors.shadow,
      shadowOpacity: 0.08,
      shadowOffset: { width: 0, height: 8 },
      shadowRadius: 14,
      elevation: 3,
    },
    summaryValue: {
      marginTop: 8,
      fontSize: 24,
      fontWeight: '700',
      color: theme.colors.textPrimary,
    },
    sectionCard: {
      borderRadius: 24,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surface,
      padding: 18,
      shadowColor: theme.colors.shadow,
      shadowOpacity: 0.08,
      shadowOffset: { width: 0, height: 10 },
      shadowRadius: 18,
      elevation: 4,
    },
    sectionHeaderRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 12,
      marginBottom: 14,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: theme.colors.textPrimary,
    },
    emptyCard: {
      borderRadius: 18,
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderStyle: 'dashed',
      paddingVertical: 18,
      paddingHorizontal: 16,
      backgroundColor: theme.isDark ? 'rgba(15, 23, 42, 0.32)' : '#f8fafc',
      alignItems: 'center',
    },
    emptyTitle: {
      fontSize: 15,
      fontWeight: '700',
      color: theme.colors.textPrimary,
    },
    overduePill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 6,
      backgroundColor: theme.isDark ? 'rgba(245, 158, 11, 0.18)' : '#fef3c7',
      borderWidth: 1,
      borderColor: theme.isDark ? 'rgba(245, 158, 11, 0.22)' : '#fcd34d',
    },
    overduePillText: {
      fontSize: 12,
      fontWeight: '700',
      color: theme.isDark ? '#fcd34d' : '#92400e',
    },
    openIssueSummaryRow: {
      flexDirection: 'row',
      gap: 10,
      marginBottom: 14,
    },
    openIssueSummaryCard: {
      flex: 1,
      borderRadius: 18,
      paddingVertical: 14,
      paddingHorizontal: 12,
      backgroundColor: theme.isDark ? 'rgba(15, 23, 42, 0.36)' : '#f8fafc',
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    openIssueSummaryLabel: {
      fontSize: 12,
      color: theme.colors.textSecondary,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    openIssueSummaryValue: {
      marginTop: 6,
      fontSize: 22,
      fontWeight: '700',
      color: theme.colors.textPrimary,
    },
    issueRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
      paddingVertical: 14,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.border,
    },
    issueRowLast: {
      borderBottomWidth: 0,
    },
    issueCopy: {
      flex: 1,
    },
    issueTitle: {
      fontSize: 15,
      fontWeight: '600',
      color: theme.colors.textPrimary,
    },
    issueMeta: {
      marginTop: 4,
      fontSize: 13,
      color: theme.colors.textSecondary,
    },
    issueBadgeGroup: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'flex-end',
      gap: 8,
      maxWidth: 120,
    },
    issueBadgeWarning: {
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 6,
      backgroundColor: theme.isDark ? 'rgba(239, 68, 68, 0.18)' : '#fee2e2',
      borderWidth: 1,
      borderColor: theme.isDark ? 'rgba(248, 113, 113, 0.24)' : '#fecaca',
    },
    issueBadgeWarningText: {
      fontSize: 12,
      fontWeight: '700',
      color: theme.isDark ? '#fca5a5' : '#b91c1c',
    },
    issueBadgeNeutral: {
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 6,
      backgroundColor: theme.isDark ? 'rgba(148, 163, 184, 0.14)' : '#e2e8f0',
    },
    issueBadgeNeutralText: {
      fontSize: 12,
      fontWeight: '700',
      color: theme.colors.textPrimary,
    },
  });
