import { StyleSheet } from 'react-native';

import type { AppTheme } from '@/theme/colors';

export const createStyles = (theme: AppTheme) => StyleSheet.create({
  centeredCard: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 180,
    paddingHorizontal: 32,
  },
  emptyIconShell: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  emptyTitleText: {
    textAlign: 'center',
    fontSize: 15,
    color: theme.colors.textPrimary,
    fontWeight: '600',
    lineHeight: 21,
  },
  emptyState: {
    marginTop: 4,
    textAlign: 'center',
    fontSize: 14,
    color: theme.colors.textSecondary,
    fontWeight: '500',
    lineHeight: 21,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 4,
    gap: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: theme.colors.border,
  },
  rowPriority: {
    backgroundColor: theme.colors.prioritySurface,
    borderRadius: 16,
    marginHorizontal: -4,
    paddingHorizontal: 8,
    borderBottomColor: theme.colors.priorityBorder,
  },
  lastRow: {
    borderBottomWidth: 0,
    paddingBottom: 4,
  },
  rowPressed: {
    opacity: 0.88,
  },
  checkboxTouchArea: {
    padding: 4,
    borderRadius: 8,
  },
  checkboxPressed: {
    opacity: 0.7,
    transform: [{ scale: 0.95 }],
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: theme.colors.inputBorder,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.inputBackground,
    shadowColor: theme.colors.shadow,
    shadowOpacity: 1,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 1 },
  },
  checkboxPriority: {
    borderColor: theme.colors.priorityBorder,
    backgroundColor: theme.colors.prioritySurface,
    shadowColor: theme.colors.priorityBorder,
  },
  checkboxDone: {
    backgroundColor: '#009689',
    borderColor: theme.colors.tabBarActiveBorder,
    shadowColor: 'rgba(0, 118, 111, 0.28)',
  },
  contentArea: {
    flex: 1,
    paddingVertical: 4,
    paddingHorizontal: 4,
  },
  contentAreaPressed: {
    opacity: 0.7,
  },
  rowLabel: {
    fontSize: 16,
    lineHeight: 22,
    color: theme.colors.textPrimary,
    fontWeight: '600',
  },
  rowLabelPriority: {
    color: '#ff6467',
  },
  rowLabelDone: {
    color: theme.colors.textMuted,
    textDecorationLine: 'line-through',
  },
  rowMeta: {
    marginTop: 4,
    fontSize: 12,
    lineHeight: 16,
    color: theme.colors.textSecondary,
  },
  badgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 8,
  },
  categoryBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
    backgroundColor: theme.colors.surfaceMuted,
  },
  categoryBadgeDot: {
    width: 7,
    height: 7,
    borderRadius: 999,
    marginRight: 6,
  },
  badgeText: {
    fontSize: 11,
    fontWeight: '600',
    color: theme.colors.textSecondary,
  },
  priorityIndicatorWrap: {
    alignSelf: 'flex-start',
    alignItems: 'center',
    justifyContent: 'center',
    width: 14,
    height: 14,
    marginLeft: 8,
    marginTop: 4,
  },
  deleteActionContainer: {
    width: 72,
    alignItems: 'flex-end',
    justifyContent: 'center',
    paddingRight: 6,
    paddingVertical: 6,
  },
  deleteAction: {
    width: 32,
    height: 32,
    borderRadius: 18,
    backgroundColor: theme.colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteActionPressed: {
    opacity: 0.85,
  },
});
