import { Dimensions, StyleSheet } from 'react-native';

import { palette } from '@/theme/colors';

const windowHeight = Dimensions.get('window').height;
export const SHEET_MAX_HEIGHT = windowHeight * 0.7;

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#f5f5f2',
  },
  headerContainer: {
    paddingHorizontal: 18,
  },
  headerCard: {
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.72)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.34)',
    shadowColor: 'rgba(15, 23, 42, 0.12)',
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 32,
    elevation: 10,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  headerCenterContent: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerSummary: {
    fontSize: 15,
    fontWeight: '400',
    lineHeight: 22,
    letterSpacing: -0.1,
    color: palette.slate900,
  },
  headerSummaryValue: {
    color: palette.slate900,
  },
  headerSummaryMuted: {
    color: palette.slate500,
  },
  headerCaption: {
    marginTop: 1,
    fontSize: 11,
    fontWeight: '500',
    textAlign: 'center',
    color: palette.slate600,
  },
  headerIconButton: {
    width: 36,
    height: 36,
    borderRadius: 14,
    backgroundColor: palette.lightSurface,
    borderWidth: 1,
    borderColor: palette.lightBorder,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: 'rgba(15, 23, 42, 0.12)',
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 16,
    elevation: 8,
  },
  headerIconButtonPressed: {
    opacity: 0.84,
  },
  scroll: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 20,
    gap: 28,
  },
  contentWithTopSpacing: {
    paddingTop: 16,
  },
  advancedFilters: {
    paddingTop: 12,
    gap: 16,
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  filterChip: {
    minHeight: 34,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.18)',
    backgroundColor: 'rgba(255, 255, 255, 0.96)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    shadowColor: 'rgba(15, 23, 42, 0.06)',
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 10,
  },
  filterChipActive: {
    backgroundColor: '#111827',
    borderColor: '#111827',
    shadowColor: 'rgba(15, 23, 42, 0.16)',
  },
  filterChipPressed: {
    opacity: 0.9,
  },
  filterChipContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  filterChipDot: {
    width: 7,
    height: 7,
    borderRadius: 999,
    marginRight: 8,
  },
  filterChipText: {
    fontSize: 12,
    fontWeight: '600',
    color: palette.slate600,
  },
  filterChipTextActive: {
    color: palette.lightSurface,
  },
  filterChipClose: {
    marginLeft: 8,
  },
  filterActionsRow: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
    paddingRight: 8,
  },
  filterAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: palette.lightBorder,
    borderRadius: 16,
    paddingVertical: 10,
    paddingHorizontal: 14,
    backgroundColor: palette.lightSurface,
  },
  filterActionActive: {
    borderColor: '#111827',
    backgroundColor: '#111827',
  },
  filterActionPressed: {
    opacity: 0.9,
  },
  filterActionText: {
    fontSize: 13,
    fontWeight: '600',
    color: palette.slate600,
  },
  filterActionTextActive: {
    color: palette.lightSurface,
  },
  clearFiltersButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.35)',
    borderRadius: 16,
    paddingVertical: 10,
    paddingHorizontal: 14,
    backgroundColor: 'rgba(239, 68, 68, 0.08)',
  },
  clearFiltersText: {
    fontSize: 13,
    fontWeight: '600',
    color: palette.danger,
  },
  fab: {
    position: 'absolute',
    right: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.mint,
    shadowColor: palette.mint,
    shadowOpacity: 0.5,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    zIndex: 30,
    elevation: 10,
  },
  fabPressed: {
    transform: [{ scale: 0.98 }],
  },
  searchDockHost: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    pointerEvents: 'box-none',
  },
  searchDock: {
    marginHorizontal: 16,
    borderRadius: 20,
    backgroundColor: '#d3d6dd',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 10,
  },
  searchDockField: {
    flex: 1,
    minHeight: 36,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(228, 228, 231, 0.8)',
    backgroundColor: palette.lightSurface,
    justifyContent: 'center',
    paddingLeft: 40,
    paddingRight: 14,
    shadowColor: 'rgba(0, 0, 0, 0.1)',
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 1 },
    shadowRadius: 3,
    elevation: 2,
  },
  searchDockIcon: {
    position: 'absolute',
    left: 14,
    top: '50%',
    marginTop: -8,
  },
  searchDockInput: {
    flex: 1,
    minHeight: 36,
    fontSize: 15,
    color: palette.slate900,
    paddingVertical: 0,
  },
  searchDockAction: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(228, 228, 231, 0.8)',
    backgroundColor: palette.lightSurface,
    shadowColor: 'rgba(0, 0, 0, 0.1)',
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 1 },
    shadowRadius: 3,
    elevation: 2,
  },
  searchDockActionPressed: {
    opacity: 0.82,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.4)',
    justifyContent: 'flex-end',
  },
  sheetContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
  },
  keyboardAvoid: {
    width: '100%',
  },
  modalWrapper: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalFlex: {
    flex: 1,
  },
  modalSheet: {
    backgroundColor: palette.lightSurface,
    paddingHorizontal: 24,
    paddingTop: 20,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderWidth: 1,
    borderColor: palette.lightBorder,
    shadowColor: palette.lightShadow,
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: -8 },
    shadowRadius: 24,
    elevation: 24,
    maxHeight: SHEET_MAX_HEIGHT,
  },
  modalScroll: {
    flexGrow: 0,
    maxHeight: SHEET_MAX_HEIGHT - 120,
  },
  modalScrollContent: {
    paddingBottom: 16,
  },
  sheetHandle: {
    alignSelf: 'center',
    width: 48,
    height: 5,
    borderRadius: 3,
    backgroundColor: palette.lightBorder,
    marginBottom: 16,
  },
  sheetClose: {
    position: 'absolute',
    top: 20,
    right: 24,
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.lightMuted,
  },
  sheetTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: palette.slate900,
    marginBottom: 4,
  },
  sheetSubtitle: {
    marginBottom: 20,
    color: palette.slate600,
    fontSize: 14,
    lineHeight: 20,
  },
  sheetSection: {
    marginBottom: 20,
  },
  sheetLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: palette.slate600,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    marginBottom: 12,
  },
  sheetInput: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: palette.lightBorder,
    backgroundColor: palette.lightMuted,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    minHeight: 100,
    maxHeight: 140,
    color: palette.slate900,
  },
  segmentGroup: {
    flexDirection: 'row',
    gap: 10,
  },
  segment: {
    flex: 1,
    height: 48,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: palette.lightBorder,
    backgroundColor: palette.lightSurface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  segmentSelected: {
    backgroundColor: palette.mintMuted,
    borderColor: palette.mint,
  },
  segmentPressed: {
    opacity: 0.85,
  },
  segmentLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: palette.slate600,
  },
  segmentLabelSelected: {
    color: palette.mintStrong,
  },
  metaRow: {
    flexDirection: 'row',
    gap: 16,
    marginBottom: 20,
    flexWrap: 'wrap',
  },
  metaColumn: {
    flexBasis: '48%',
    flexGrow: 1,
    gap: 12,
  },
  metaButton: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: palette.lightBorder,
    borderRadius: 18,
    paddingVertical: 14,
    paddingHorizontal: 14,
    backgroundColor: palette.lightSurface,
  },
  metaButtonPressed: {
    opacity: 0.9,
  },
  metaIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  metaIconNeutral: {
    borderColor: palette.lightBorder,
    backgroundColor: palette.lightMuted,
  },
  metaCopy: {
    flex: 1,
    marginLeft: 12,
  },
  metaTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: palette.slate900,
  },
  metaSubtitle: {
    fontSize: 13,
    color: palette.slate600,
    marginTop: 2,
  },
  createButton: {
    marginTop: 8,
    borderRadius: 16,
    backgroundColor: palette.mint,
    paddingVertical: 16,
    alignItems: 'center',
  },
  createButtonDisabled: {
    backgroundColor: palette.mintMuted,
  },
  createButtonPressed: {
    transform: [{ scale: 0.98 }],
  },
  createButtonLabel: {
    fontSize: 16,
    fontWeight: '700',
    color: palette.lightSurface,
  },
  optionSheet: {
    backgroundColor: palette.lightSurface,
    paddingHorizontal: 24,
    paddingTop: 20,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderWidth: 1,
    borderColor: palette.lightBorder,
    shadowColor: palette.lightShadow,
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: -8 },
    shadowRadius: 24,
    elevation: 24,
    maxHeight: SHEET_MAX_HEIGHT,
  },
  optionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: palette.slate900,
    textAlign: 'center',
  },
  optionSubtitle: {
    marginTop: 6,
    fontSize: 14,
    color: palette.slate600,
    textAlign: 'center',
    marginBottom: 20,
  },
  optionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: palette.lightBorder,
    paddingVertical: 14,
    paddingHorizontal: 14,
    marginBottom: 12,
    backgroundColor: palette.lightSurface,
  },
  optionItemActive: {
    borderColor: palette.mint,
  },
  optionItemPressed: {
    opacity: 0.9,
  },
  optionCopy: {
    flex: 1,
    marginLeft: 12,
  },
  optionLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: palette.slate900,
  },
  optionCaption: {
    fontSize: 13,
    color: palette.slate600,
    marginTop: 2,
  },
  categorySearch: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderWidth: 1,
    borderColor: palette.lightBorder,
    borderRadius: 16,
    backgroundColor: palette.lightMuted,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 16,
  },
  categoryInput: {
    flex: 1,
    fontSize: 15,
    color: palette.slate900,
    paddingVertical: 0,
  },
  categoryList: {
    maxHeight: 260,
  },
});
